cc_binary(
    name="binary_search_tree",
    srcs=[
        "binary_search_tree.cpp",
    ],
)

cc_binary(
    name="convex_hull",
    srcs=[
        "convex_hull.cpp",
    ],
)


cc_binary(
    name="nearest_meeting_point_circular",
    srcs=[
        "nearest_meeting_point_circular.cpp",
    ],
)